use crate::models::{AuditEvent, PackageSnapshot, PolicyConfig};

pub fn package_snapshots() -> Vec<PackageSnapshot> {
    vec![
        PackageSnapshot {
            id: "pkg-fastapi".into(),
            package_name: "fastapi".into(),
            ecosystem: "python".into(),
            current_version: "0.109.0".into(),
            latest_version: "0.116.1".into(),
            release_gap: 7,
            lockfile_age_days: 43,
            owner: "Platform APIs".into(),
            service_tier: "tier-1".into(),
            adoption_scope: "decision engines".into(),
            cve_signals: 1,
            breaking_changes_pending: false,
            automated_updates: true,
        },
        PackageSnapshot {
            id: "pkg-axum".into(),
            package_name: "axum".into(),
            ecosystem: "rust".into(),
            current_version: "0.7.4".into(),
            latest_version: "0.8.6".into(),
            release_gap: 4,
            lockfile_age_days: 28,
            owner: "Platform Reliability".into(),
            service_tier: "tier-1".into(),
            adoption_scope: "rust exporters".into(),
            cve_signals: 0,
            breaking_changes_pending: true,
            automated_updates: false,
        },
        PackageSnapshot {
            id: "pkg-next".into(),
            package_name: "next".into(),
            ecosystem: "node".into(),
            current_version: "14.1.2".into(),
            latest_version: "15.3.2".into(),
            release_gap: 9,
            lockfile_age_days: 62,
            owner: "Growth Web".into(),
            service_tier: "tier-1".into(),
            adoption_scope: "headless frontends".into(),
            cve_signals: 2,
            breaking_changes_pending: true,
            automated_updates: false,
        },
        PackageSnapshot {
            id: "pkg-opentelemetry".into(),
            package_name: "opentelemetry-sdk".into(),
            ecosystem: "python".into(),
            current_version: "1.25.0".into(),
            latest_version: "1.34.0".into(),
            release_gap: 6,
            lockfile_age_days: 31,
            owner: "Observability".into(),
            service_tier: "tier-1".into(),
            adoption_scope: "telemetry collectors".into(),
            cve_signals: 0,
            breaking_changes_pending: false,
            automated_updates: true,
        },
        PackageSnapshot {
            id: "pkg-log4j".into(),
            package_name: "log4j-core".into(),
            ecosystem: "java".into(),
            current_version: "2.19.0".into(),
            latest_version: "2.24.3".into(),
            release_gap: 5,
            lockfile_age_days: 118,
            owner: "Enterprise Integrations".into(),
            service_tier: "tier-0".into(),
            adoption_scope: "workflow connectors".into(),
            cve_signals: 3,
            breaking_changes_pending: false,
            automated_updates: false,
        },
        PackageSnapshot {
            id: "pkg-react".into(),
            package_name: "react".into(),
            ecosystem: "node".into(),
            current_version: "18.2.0".into(),
            latest_version: "19.1.0".into(),
            release_gap: 3,
            lockfile_age_days: 74,
            owner: "Growth Web".into(),
            service_tier: "tier-2".into(),
            adoption_scope: "studio surfaces".into(),
            cve_signals: 0,
            breaking_changes_pending: true,
            automated_updates: false,
        },
    ]
}

pub fn policy_config() -> PolicyConfig {
    PolicyConfig {
        scan_interval_hours: 12,
        freshness_window_days: 30,
        critical_gap_threshold: 6,
        allowed_owners: vec![
            "Platform APIs".into(),
            "Platform Reliability".into(),
            "Growth Web".into(),
            "Observability".into(),
            "Enterprise Integrations".into(),
        ],
        alert_targets: vec![
            "slack://dependency-watch".into(),
            "pagerduty://platform-reliability".into(),
            "github://dependabot-review".into(),
        ],
    }
}

pub fn audit_log() -> Vec<AuditEvent> {
    vec![
        AuditEvent {
            timestamp: "2026-05-15 08:10:14".into(),
            action: "DRIFT_SCAN_STARTED".into(),
            resource: "workspace://production-lockfiles".into(),
            result: "success".into(),
            detail: "Dependency drift watch started a fresh comparison against current release channels.".into(),
        },
        AuditEvent {
            timestamp: "2026-05-15 08:10:49".into(),
            action: "CRITICAL_GAP_FLAGGED".into(),
            resource: "log4j-core".into(),
            result: "warning".into(),
            detail: "A tier-0 integration package crossed the critical release-gap and CVE threshold.".into(),
        },
        AuditEvent {
            timestamp: "2026-05-15 08:11:03".into(),
            action: "BREAKING_CHANGE_DETECTED".into(),
            resource: "next".into(),
            result: "warning".into(),
            detail: "Frontend lane drift includes a major-version jump that should not auto-promote without owner review.".into(),
        },
        AuditEvent {
            timestamp: "2026-05-15 08:11:26".into(),
            action: "OWNER_LANE_RANKED".into(),
            resource: "Growth Web".into(),
            result: "success".into(),
            detail: "Owner-lane scoring elevated Growth Web due to stacked release lag across headless frontend packages.".into(),
        },
        AuditEvent {
            timestamp: "2026-05-15 08:11:57".into(),
            action: "RECOMMENDATION_EMITTED".into(),
            resource: "tier-0-and-tier-1".into(),
            result: "success".into(),
            detail: "Lead recommendation issued: clear Java and frontend drift before the next release window compounds risk.".into(),
        },
    ]
}
